# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filtro_imagem.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66iltro_imagem.proto\"I\n\x12UploadImageRequest\x12\x0e\n\x06imagem\x18\x01 \x01(\x0c\x12\x13\n\x0bnome_imagem\x18\x02 \x01(\t\x12\x0e\n\x06\x66iltro\x18\x03 \x01(\x05\")\n\rImageResponse\x12\x18\n\x10imagemModificada\x18\x01 \x01(\x0c\x32=\n\x06\x66iltro\x12\x33\n\x0c\x61plicaFiltro\x12\x13.UploadImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filtro_imagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADIMAGEREQUEST']._serialized_start=23
  _globals['_UPLOADIMAGEREQUEST']._serialized_end=96
  _globals['_IMAGERESPONSE']._serialized_start=98
  _globals['_IMAGERESPONSE']._serialized_end=139
  _globals['_FILTRO']._serialized_start=141
  _globals['_FILTRO']._serialized_end=202
# @@protoc_insertion_point(module_scope)
